POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Janne Kerola",
    "number": "123 456 789"
}

### INVALID POST

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ja",
    "number": "123 456 789"
}


### INVALID POST 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Janne",
    "number": "123 456"
}